### ISSUE TITLE
Cannot get 1.5.31 to work at all

### ISSUE THREAD

**Issue by getutsav** [AndMu/YiScanner#14] opened 2019-02-27 22:27 UTC
Hello,
I've looked at the other issues you have closed and tried the solutions you have listed but I still cannot get this to work. My camera is accessible via ftp at 192.168.200.12 with username root and null password. 

I've tried the command:
Wikiled.YiScanner.exe Download -Cameras=1080i -Hosts=192.168.200.12 -Out=c:\out

The output I get is:
C:\Users\Utsav Agarwal\Desktop\YI Blue Iris Experiment\YiScanner.1.5.31>Wikiled.YiScanner.exe Download -Cameras=1080i -Hosts=192.168.200.12 -Out=c:\out
Starting 1.5.31.0 version utility...
Starting on local IP: [192.168.0.102]
Starting camera download...
Downloading...
Archiving...
Checking files: C:\Users\Utsav Agarwal\Desktop\YI Blue Iris Experiment\YiScanner.1.5.31\CCTV
Completed: C:\Users\Utsav Agarwal\Desktop\YI Blue Iris Experiment\YiScanner.1.5.31\CCTV

I get no files in "c:\out or in CCTV"

I don't understand what I'm doing wrong. My .NET 4.6.2 is up to date and I'm running Windows 10 x64.

Please help me get this to work. Also would the file structure be maintained when the files are being copied over or will the .mp4 files just be dumped together?

**Comment by AndMu** [comment] 2019-02-27 23:29
Can you enable debug logging in nlog.config? change line
 <logger name="*" minlevel="Info" writeTo="c,f" />
to 
 <logger name="*" minlevel="Debug" writeTo="c,f" />

And attach log file on this issue.

**Comment by AndMu** [comment] 2019-02-27 23:32
Also have you tried using service.json configuration and running without arguments?

**Comment by AndMu** [comment] 2019-02-27 23:55
I think the issue is with service.json configuration. 
Looks like in the latest version it overrides supplied arguments. I will fix this issue tomorrow.

As a temporary solution, if you want to use using arguments specify additional argument:
Wikiled.YiScanner.exe Download -Cameras=1080i -Hosts=192.168.200.12 -Out=c:\out -AutoDiscover=false

**Comment by AndMu** [comment] 2019-02-28 11:08
Fixed in v1.5.85

**Closed by AndMu** 2019-02-28 11:08 UTC

**Comment by getutsav** [comment] 2019-02-28 21:51
Thanks for the quick fix but now I seem to be having a problem with the program running as a service. I installed it and ran the service and the logs say that its running fine but it does not seem to be getting any new files even though there are new files in the SD card of the camera. I have verified that by manually FTPing into the camera.

Should I make a new issue ? Do you need me to provide you with anything that might help you diagnose the problem ?

**Comment by AndMu** [comment] 2019-02-28 22:27
Can you change in 
nlog.config
logger name="*" minlevel="**Info**" writeTo="c,f"
to 
logger name="*" minlevel="**Debug**" writeTo="c,f"

Leave it running for an hour and send a log file from folder Logs\trace.log
Also please attach you service.json file

**Comment by getutsav** [comment] 2019-03-01 01:01
I think I have figured out the problem. The command that you provided to add cameras manually does not work correctly. If I turn off auto discovery and put in the ""Known":{ "Cameras": "1080i", "Hosts": "192.168.0.22" }" command into the json file the program does not find the camera. But if I remove the known command and turn auto discovery on the program immediately finds the camera and starts downloading from it. 
The service.json where the camera connects and downloads work is: 

{
  "Scan": 30,
  "Timeout": 1200,
  "Output": {
    "Compress": false,
    "Images": false,
    "Out": "L:/Yi"
  },
  "Archive": 5,
  "Action": null,
  "AutoDiscovery": {
    "On": true,
    "NetworkMask": "192.168.200.0/255.255.255.0"
  },

  "YiFtp": {
    "Path": "/tmp/sd/record/",
    "Password": "",
    "Login": "root",
    "FileMask": "*.mp4"
  },

  "Server": {
    "Path": "CCTV",
	"Port": 21
  },
  
 
}

The service.json where the camera cannot be connected to is:

{
  "Scan": 30,
  "Timeout": 1200,
  "Output": {
    "Compress": false,
    "Images": false,
    "Out": "L:/Yi"
  },
  "Archive": 5,
  "Action": null,
  "AutoDiscovery": {
    "On": true,
    "NetworkMask": "192.168.0.0/255.255.255.0"
  },

  "YiFtp": {
    "Path": "/tmp/sd/record/",
    "Password": "",
    "Login": "root",
    "FileMask": "*.mp4"
  },

  "Server": {
    "Path": "CCTV",
	"Port": 21
  },
  
  "Known":{ "Cameras": "1080i", "Hosts": "192.168.200.12" }
 
}

**Comment by getutsav** [comment] 2019-03-01 01:03
I think I have figured out the problem. The command that you provided to add cameras manually does not work correctly. If I turn off auto discovery and put in the ""Known":{ "Cameras": "1080i", "Hosts": "192.168.0.22" }" command into the json file the program does not find the camera. But if I remove the known command and turn auto discovery on the program immediately finds the camera and starts downloading from it.
The service.json where the camera connects and downloads work is:

{
"Scan": 30,
"Timeout": 1200,
"Output": {
"Compress": false,
"Images": false,
"Out": "L:/Yi"
},
"Archive": 5,
"Action": null,
"AutoDiscovery": {
"On": true,
"NetworkMask": "192.168.200.0/255.255.255.0"
},

"YiFtp": {
"Path": "/tmp/sd/record/",
"Password": "",
"Login": "root",
"FileMask": "*.mp4"
},

"Server": {
"Path": "CCTV",
"Port": 21
},

}

The service.json where the camera cannot be connected to is:

{
"Scan": 30,
"Timeout": 1200,
"Output": {
"Compress": false,
"Images": false,
"Out": "L:/Yi"
},
"Archive": 5,
"Action": null,
"AutoDiscovery": {
"On": false,
"NetworkMask": "192.168.0.0/255.255.255.0"
},

"YiFtp": {
"Path": "/tmp/sd/record/",
"Password": "",
"Login": "root",
"FileMask": "*.mp4"
},

"Server": {
"Path": "CCTV",
"Port": 21
},

"Known":{ "Cameras": "1080i", "Hosts": "192.168.200.12" }

}

**Comment by getutsav** [comment] 2019-03-01 01:37
Actually got it to work. Apparently the program does not like it if I add the Known part at the bottom of the file. If I add it above Auto Discovery and turn Auto Discovery off and run it, it works. It finds the camera, connects to it and downloads all files successfully. 

After seeing that the program actually connects, I tried to run it as a service and the program still works. So now it completely works on my end. 

Thanks for your efforts in getting back to me so quickly, and I suggest that you add a disclaimer in your readme for people like me who would manually add cameras that the command cannot be added to the end of the file. It needs to be up top. 

Thanks again!!

The completely working service.json that also successfully works as a service as well is:

{
  "Scan": 30,
  "Timeout": 1200,
  "Output": {
    "Compress": false,
    "Images": false,
    "Out": "L:/Yi"
  },
  "Archive": 7,
  "Action": null,
  
  "Known": { 
	"Cameras": "Verandah",
	"Hosts": "192.168.200.12" 
  },
  
  "AutoDiscovery": {
    "On": false,
    "NetworkMask": "192.168.0.0/255.255.255.0"
  },

  "YiFtp": {
    "Path": "/tmp/sd/record/",
    "Password": "",
    "Login": "root",
    "FileMask": "*.mp4"
  },

  "Server": {
    "Path": "CCTV",
	"Port": 21
  },
}

**Comment by AndMu** [comment] 2019-03-01 18:29
A sequence is not important in the configuration file. However, too many different things are configured.
As an example you don't need autodiscovery block if you are using static configuration. 
You don't need to run FTP server either for YI cameras.
In you case your configuration should be as simple as:
`{
  "Scan": 30,
  "Timeout": 1200,
  "Output": {
    "Compress": false,
    "Images": false,
    "Out": "L:/Yi"
  },

  "Archive": 5,

  "YiFtp": {
    "Path": "/tmp/sd/record/",
    "Password": "",
    "Login": "root",
    "FileMask": "*.mp4"
  },
  
  "Known": {
    "Cameras": "1080i",
    "Hosts": "192.168.200.12"
  }
}`

I will update readme to indicate simplest configuration

**Comment by getutsav** [comment] 2019-03-01 18:59
Aah, thanks for the clarification! 
Thank you for this lovely piece of code 👍 :)
